In [1]:
import numpy as np
a = np.array([1,4,2,3,5,7,8,6])
print(a)

[1 4 2 3 5 7 8 6]


In [2]:
# for 2D arry
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b)

[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


In [3]:
np.zeros
np.ones
np.full
np.random.random
print(np.zeros((2, 2)))

[[0. 0.]
 [0. 0.]]


In [10]:
print(np.ones((1,2)))

print(np.full((2,2),7))

[[1. 1.]]
[[7 7]
 [7 7]]


In [16]:
np.random.seed(42)
c = np.random.random((2, 2))
print(c)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [17]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [20]:
#reading documentataion in python
help(np.random.random)


Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [21]:
#features of Numpy arrays
#shape
a = np.array([1,4,2,3,5,7,8,6]) #output 1D array with 8 elements
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]]) #define 2D array with 3rows and 6 columns
print(a.shape)
print(b.shape)

(8,)
(3, 6)


In [22]:
# size
a = np.array([1,4,2,3,5,7,8,6]) # o/p confirms total no. elements in arr
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]]) 
print(a.size)
print(b.size)

8
18


In [23]:
a = np.array([1,4,2,3,5,7,8,6]) #o/p confirms 1D arry 
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]]) #o/p confirms 2D arry
print(a.ndim)
print(b.ndim)

1
2


In [24]:
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
np.random.seed(42)
c = np.random.random((2, 2))
print(a.dtype.name)
print(b.dtype.name)
print(c.dtype.name)

int32
int32
float64


In [25]:
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
np.random.seed(42)
c = np.random.random((2, 2))
print(a.itemsize) # o/p confirms size individual arr elements
print(b.itemsize)
print(c.itemsize)

4
4
8


In [26]:
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
np.random.seed(42)
c = np.random.random((2, 2))
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [27]:
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
np.random.seed(42)
c = np.random.random((2, 2))
print(np.zeros(b.shape))# create an arr of zeros of size b

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [28]:
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
np.random.seed(42)
c = np.random.random((2, 2))
print(np.ones(a.shape))# create of arr of a shape

[1. 1. 1. 1. 1. 1. 1. 1.]
