In [ ]:
#a[i] -> element at index i
#a[0] -> first elemt at 0 index
#a[1] -> second elemt at 1 index
#Numpy
#Advantages of numpy
#array oriented computing
#efficiently implemented multi-dimensionals array
# designed for scientific computation
#sophiscated functions for initializing, indexing,slicing





In [2]:
import numpy as np
a = np.array([1,4,2,3,5,7,8,6])
print(a[0])

1


In [3]:
# pull out elements start at 2 end at 4
a = np.array([1,4,2,3,5,7,8,6])
print(a[2:4])

[2 3]


In [4]:
#pull out first 3 elemenst
a = np.array([1,4,2,3,5,7,8,6])
print(a[:3])

[1 4 2]


In [5]:
# 2D arry elements
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b[:2, 1:3])

[[0 1]
 [3 0]]


In [6]:
# pull out first 2 rows ana all cols
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b[1:2, :])

[[1 3 0 1 2 0]]


In [8]:
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b[:,2])

[1 0 0]


In [10]:
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b)
b[0, 0] = 7 # modify value at 0,0
print(b)

[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]
[[7 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]


In [11]:
b = np.array([[1,0,1,0,2,3], 
              [1,3,0,1,2,0], 
              [0,1,0,0,1,3]])
print(b)
b[1:3, 2:4] = 9 #modify the value of 9 at row 2 and 3 and column 3 and 4
print(b)

[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]
[[1 0 1 0 2 3]
 [1 3 9 9 2 0]
 [0 1 9 9 1 3]]


In [12]:
b = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b)
b[:2, 1:3] = np.array([[2, 0], [4, 3]]) # modify elements from different array with the same shape the array we select
print(b)

[[1 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]
[[1 2 0 0 2 3]
 [1 4 3 1 2 0]
 [0 1 0 0 1 3]]


In [13]:
# conditional indexing
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[7,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(a)
print(a > 2)



[1 4 2 3 5 7 8 6]
[False  True False  True  True  True  True  True]


In [14]:
a = np.array([1,4,2,3,5,7,8,6])
b = np.array([[7,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
print(b)
print(b > 2)
print(b[b > 2])

[[7 0 1 0 2 3]
 [1 3 0 1 2 0]
 [0 1 0 0 1 3]]
[[ True False False False False  True]
 [False  True False False False False]
 [False False False False False  True]]
[7 3 3 3]
